### PR TITLE
Update pickaprint.sh

### PR DESCRIPTION
**Pull request by daboynb**
Hi, on my device I got the error unzip not found, this fixes the issue.

### CODE REVIEW

**Comment by TheFreeman193** [comment]
Hi @daboynb, thanks for pointing this out. Due to that fact this specific line change would break functionality for devices using other rooting methods such as KSU, I'll need to implement binary path detection as with `wget`/`curl` to improve compatibility.

I already have some changes to the script in the works so I'll add this in and tag you as a coauthor on that commit.

**Comment by daboynb** [comment]
Perfect, thank you

**Comment by daboynb** [comment]
Hi, I just want to add two things :

- I was getting "pickaprint.sh[129]: grep: not found" and I solved it by changing "grep" to "/system/bin/grep"
- I was getting "pickaprint.sh[129]: [: FORCEABI: unexpected operator/operand" and I solved it by changing "if [ -v FORCEABI ]; then" to "if [ -n FORCEABI ]; then"

**Comment by TheFreeman193** [comment]
@daboynb Thanks for these added observations. The latest version of the script will attempt to use busybox if available which should provide much more consistent results (busybox ships with both Magisk and KSU). I've also replaced the variable-set conditional as per your second point, though I should add that your change above will always return `true` because the dollar sign is missing before `FORCEABI`. I'll let you know when I push the new version out. 🙂

**Comment by daboynb** [comment]
Perfect, thank you again :)

I saw it now -> https://github.com/TheFreeman193/PIFS/pull/1/commits/3b75d2b01f841d4aea83d6333471f63e32cdea08 this was my last commit, I wrote the wrong fix on my previous post ahah

**Pull request closed without merging**
